import asyncio
import logging
from app.meta_api import meta_api

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("send_catalog")

async def send_catalog_to_fazal():
    phone = "919265368695"
    logger.info(f"Delivering full 5-part message catalog to Fazal ({phone})...")

    # PART 1
    part1 = (
        "📜 *TAGONESWA COMPLETE MESSAGE CATALOG (PART 1 OF 5)*\n"
        "════════════════════════════\n"
        "*STAGE 1: SALES REP — ENTRY & SHORTFALL RESOLUTION*\n\n"
        "1️⃣ *Sales Portal Entry Menu (Button Card):*\n"
        "Header: `TAGONESWA SALES PORTAL`\n"
        "Body:\n"
        "👋 *TAGONESWA SALES PORTAL*\n"
        "────────────────────\n"
        "Welcome Tinashe (Sales Rep)!\n"
        "Please select an option below:\n"
        "Buttons: `[Fleet Trip Approval]`, `[Pending Balance]`, `[IT Support]`\n\n"
        "2️⃣ *Company Selection Prompt (Button Card):*\n"
        "Header: `SELECT COMPANY`\n"
        "Body:\n"
        "🏢 *SELECT OPERATING COMPANY*\n"
        "────────────────────\n"
        "Which operating company is this trip for?\n"
        "• Auto-routes return balancing to this company's assigned Sales Admin.\n"
        "Buttons: `[A. TG Hardware]`, `[B. LG Plast]`, `[C. Kreckle]`\n\n"
        "3️⃣ *Trip ID Input Prompt (Text):*\n"
        "🚛 *FLEET TRIP APPROVAL: A. TG Hardware*\n"
        "────────────────────\n"
        "Please enter the *Trip ID* from Favlogix:\n"
        "_(e.g. 20042026-BINDURA or TRIP-2026-00456)_\n"
        "💡 _Reply 'cancel' to return to the main menu._\n"
        "👉 *Sales Rep Replies:* `TRIP-2026-00456`\n\n"
        "4️⃣ *ERP Verification Notice (Text):*\n"
        "⏳ *Verifying Trip TRIP-2026-00456 with Favlogix ERP...*\n"
        "_Please wait while live order values and route thresholds are verified._\n\n"
        "5️⃣ *Clean Shortfall Decision Card (Button Card):*\n"
        "*(Route Minimum and 4% formula STRICTLY HIDDEN)*\n"
        "Header: `FLEET TRIP DETAILS`\n"
        "Body:\n"
        "📋 *FLEET TRIP DETAILS*\n"
        "────────────────────\n"
        "🏢 Company: A. TG Hardware\n"
        "🚛 Trip: `TRIP-2026-00456`\n"
        "📍 Destination: Gweru\n"
        "💰 Sales Total: $14,200.00\n"
        "💸 Transport Fee to Take: *$152.00*\n"
        "────────────────────\n"
        "Please select an option below:\n"
        "Buttons: `[Full Charge]`, `[Partial Charge]`, `[Add to Pending]`\n\n"
        "6️⃣ *Shortfall Option Execution Paths:*\n"
        "• *Full Charge:* Directly shows Stage 2 Favlogix check without asking amount.\n"
        "• *Partial Charge:* Bot asks: `💵 How much did you charge the customer? (enter USD amount, e.g. 100):` -> Rep replies `100` -> Bot: `⚖️ $100.00 charged. Remaining $52.00 added to your pending recovery balance.`\n"
        "• *Add to Pending:* Directly posts `$152.00` to pending balance without asking amount."
    )

    # PART 2
    part2 = (
        "📜 *TAGONESWA COMPLETE MESSAGE CATALOG (PART 2 OF 5)*\n"
        "════════════════════════════\n"
        "*STAGE 2: FAVLOGIX CONFIRMATION & MANIFEST*\n\n"
        "1️⃣ *Favlogix Charges Check (Button Card):*\n"
        "Header: `FAVLOGIX CHARGES`\n"
        "Body:\n"
        "💵 *FULL TRANSPORT CHARGE SELECTED*\n"
        "Trip: `TRIP-2026-00456` | Transport Fee: $152.00\n"
        "────────────────────\n"
        "Please charge all customers in Favlogix and select YES when done:\n"
        "Buttons: `[YES]`, `[NO]`\n"
        "*(If NO selected -> Bot prompts to charge first and re-shows [YES])*.\n\n"
        "2️⃣ *Customer Manifest Registration (Text):*\n"
        "📋 *CUSTOMER CHARGES MANIFEST: TRIP-2026-00456*\n"
        "────────────────────\n"
        "To verify customer charges autonomously during driver transit, please enter customer charges in this format:\n"
        "👉 `CUST-101: 45, CUST-102: 60`\n"
        "_(or type *SKIP* if charging a single general customer)_\n"
        "👉 *Sales Rep Replies:* `CUST-101: 45, CUST-102: 60, CUST-103: 47`\n\n"
        "3️⃣ *Manifest Saved & Forwarded to Edward (Button Card):*\n"
        "Header: `DISPATCH CLEARED`\n"
        "Body:\n"
        "✅ *TRIP DISPATCH CLEARED: TRIP-2026-00456*\n"
        "────────────────────\n"
        "Company: A. TG Hardware\n"
        "Route: Gweru\n"
        "Registered Customers: 3\n"
        "────────────────────\n"
        "Order is cleared! Notification forwarded to Edward for truck and driver allocation. 🚛💨\n"
        "Buttons: `[Main Menu]`\n\n"
        "────────────────────────────\n"
        "*STAGE 3: EDWARD LOGISTICS ALLOCATION*\n"
        "*(Sales Total strictly HIDDEN from Edward)*\n\n"
        "4️⃣ *Trip Dispatch Alert to Edward (Button Card):*\n"
        "Header: `NEW TRIP DISPATCH`\n"
        "Body:\n"
        "NEW TRIP DISPATCH ALLOCATION\n"
        "────────────────────\n"
        "Company: A. TG Hardware\n"
        "Trip: TRIP-2026-00456\n"
        "Route: Gweru\n"
        "Sales Rep: Tinashe (+263772111222)\n"
        "────────────────────\n"
        "Please allocate vehicle and driver details below:\n"
        "Buttons: `[Allocate Trip]`, `[Trip Queue]`\n\n"
        "5️⃣ *Edward Step-by-Step Inputs (Typed directly, NO brackets):*\n"
        "• Step 1: `🚛 Please type the truck registration number: (e.g. ZW 123 ABC or ABL 4589)` -> Edward types: `ZW 123 ABC`\n"
        "• Step 2: `👤 Please type the driver's full name: (e.g. John Banda)` -> Edward types: `John Banda`\n"
        "• Step 3: `📱 Please type the driver's WhatsApp phone number: (e.g. 263771234567)` -> Edward types: `263779888777`\n"
        "• Step 4: `👥 Enter number of crew members: (type number, e.g. 2)` -> Edward types: `2`\n"
        "• Step 5: `🍱 Enter number of meals per person: (type number, e.g. 3)` -> Edward types: `3`\n"
        "• Step 6: `🛣️ Enter number of tolls on route: (type number, e.g. 4)` -> Edward types: `4`\n"
        "• Step 7: `💵 Enter total toll cost in USD: (e.g. 34.50 or 0)` -> Edward types: `34.50`\n\n"
        "6️⃣ *Edward Allocation Review Card (Button Card):*\n"
        "Header: `TRIP ALLOCATION`\n"
        "Body:\n"
        "TRIP ALLOCATION SUMMARY\n"
        "────────────────────\n"
        "Company: A. TG Hardware\n"
        "Trip: TRIP-2026-00456 | Route: Gweru\n"
        "Driver: John Banda | Truck: ZW 123 ABC\n"
        "Crew: 2 people | Meals: 3 | Tolls: 4\n"
        "────────────────────\n"
        "Toll cost: $34.50\n"
        "Food ($2 x 2 x 3): $12.00\n"
        "────────────────────\n"
        "Total allowance: $46.50\n"
        "Please confirm or change:\n"
        "Buttons: `[Confirm]`, `[Change]`\n\n"
        "7️⃣ *Edward Taps [Confirm]:*\n"
        "✅ *ALLOCATION CONFIRMED: TRIP-2026-00456*\n"
        "Forwarded to Zayn for allowance approval!"
    )

    # PART 3
    part3 = (
        "📜 *TAGONESWA COMPLETE MESSAGE CATALOG (PART 3 OF 5)*\n"
        "════════════════════════════\n"
        "*STAGE 4: ZAYN ALLOWANCES & ACCOUNTS PAYOUT*\n\n"
        "1️⃣ *Zayn Allowance Approval Prompt (Button Card):*\n"
        "Header: `ALLOWANCE APPROVAL NEEDED`\n"
        "Body:\n"
        "ALLOWANCE APPROVAL NEEDED\n"
        "────────────────────\n"
        "Company: A. TG Hardware\n"
        "Trip: TRIP-2026-00456 | Route: Gweru\n"
        "Driver: John Banda | Truck: ZW 123 ABC\n"
        "Crew: 2 people | Meals: 3 | Tolls: 4\n"
        "────────────────────\n"
        "Toll cost: $34.50\n"
        "Food ($2 x 2 x 3): $12.00\n"
        "────────────────────\n"
        "Total allowance: *$46.50*\n"
        "Please approve or recalculate:\n"
        "Buttons: `[Approve]`, `[Recalculate]`\n\n"
        "2️⃣ *If Zayn Taps [Recalculate]:*\n"
        "Bot prompts Zayn: `📝 Enter recalculation instructions for Edward:`\n"
        "Alert sent to Edward: `⚠️ Notes from Zayn: \"Reduce tolls to 2\" [Allocate Trip]`\n\n"
        "3️⃣ *If Zayn Taps [Approve]:*\n"
        "Bot to Zayn: `✅ ALLOWANCE APPROVED: TRIP-2026-00456 ($46.50). Notification forwarded to Accounts!`\n\n"
        "4️⃣ *Accounts Payout Notification (Button Card):*\n"
        "Header: `ALLOWANCE APPROVED`\n"
        "Body:\n"
        "ALLOWANCE APPROVED\n"
        "────────────────────\n"
        "Trip: TRIP-2026-00456\n"
        "Company: A. TG Hardware\n"
        "Driver: John Banda (+263779888777)\n"
        "Truck: ZW 123 ABC\n"
        "Total Allowance: $46.50\n"
        "(Tolls: $34.50 | Food: $12.00)\n"
        "────────────────────\n"
        "Please handle money transfer and confirm below:\n"
        "Buttons: `[Transfer Done]`\n\n"
        "5️⃣ *Accounts Taps [Transfer Done]:*\n"
        "Bot to Accounts: `✅ TRANSFER CONFIRMED: Driver John Banda notified to set departure time.`\n\n"
        "6️⃣ *Driver Prompted for Departure Time (Text):*\n"
        "💵 *ALLOWANCE TRANSFERRED: TRIP-2026-00456*\n"
        "────────────────────\n"
        "Truck: ZW 123 ABC\n"
        "Total Allowance: $46.50\n"
        "────────────────────\n"
        "Please enter your scheduled departure time:\n"
        "_(e.g. 06:30 AM or 07:00 AM)_\n"
        "👉 *Driver Replies:* `06:30 AM`\n\n"
        "────────────────────────────\n"
        "*STAGE 5: DRIVER COMMENCEMENT & LIVE LOCATION*\n\n"
        "7️⃣ *Driver Receives [Trip Started] Button Card:*\n"
        "Header: `START TRIP`\n"
        "Body:\n"
        "⏰ *DEPARTURE TIME LOGGED: 06:30 AM*\n"
        "────────────────────\n"
        "Trip: `TRIP-2026-00456`\n"
        "Truck: ZW 123 ABC\n"
        "Total Allowance: $46.50\n"
        "────────────────────\n"
        "When you begin your journey, tap 'Trip Started' below.\n"
        "(This will activate live location tracking for your Sales Rep):\n"
        "Buttons: `[Trip Started]`\n\n"
        "8️⃣ *Driver Taps [Trip Started]:*\n"
        "• *Alert to Sales Rep:* `🚛 TRIP STARTED: TRIP-2026-00456 | Driver: John Banda | Truck: ZW 123 ABC | Departure: 06:30 AM. Live location stream is now active.`"
    )

    # PART 4
    part4 = (
        "📜 *TAGONESWA COMPLETE MESSAGE CATALOG (PART 4 OF 5)*\n"
        "════════════════════════════\n"
        "*STAGE 5: IN-TRANSIT ACTIONS, COLLECTIONS & EMERGENCIES*\n\n"
        "1️⃣ *Driver In-Transit Active Menu (Button Card):*\n"
        "Header: `TRIP IN TRANSIT`\n"
        "Body:\n"
        "🚛 *TRIP IN TRANSIT: TRIP-2026-00456*\n"
        "────────────────────\n"
        "Live location tracking is active.\n"
        "Please select an option below:\n"
        "Buttons: `[Delivery Charges]`, `[Emergency Charges]`, `[I am Returning]`\n\n"
        "2️⃣ *Driver Logs Customer Delivery Fee:*\n"
        "• Driver taps `[Delivery Charges]`\n"
        "• Bot: `📦 RECORD DELIVERY CHARGE: Please enter the Customer ID: (e.g. CUST-101)`\n"
        "• Driver types: `CUST-101`\n"
        "• Bot matches Stage 2 schedule & presents payment options:\n"
        "Header: `PAYMENT METHOD`\n"
        "Body:\n"
        "💵 *RECORD PAYMENT: CUST-101*\n"
        "Expected Delivery Charge: $45.00\n"
        "────────────────────\n"
        "Please select how the customer paid:\n"
        "Buttons: `[Cash]`, `[Bank/EcoCash]`, `[Unpaid]`\n\n"
        "3️⃣ *Driver Selects Payment Method:*\n"
        "✅ *PAYMENT RECORDED*\n"
        "Customer: CUST-101 | Amount: $45.00 | Method: CASH | Status: PAID\n"
        "Delivery charge successfully logged!\n"
        "*(Bot re-displays the 3 transit buttons)*.\n\n"
        "4️⃣ *Driver Logs Emergency Expense (Button Card):*\n"
        "Header: `EMERGENCY CHARGES`\n"
        "Body:\n"
        "⚠️ *EMERGENCY CHARGES: TRIP-2026-00456*\n"
        "────────────────────\n"
        "Select the type of emergency expense:\n"
        "Buttons: `[Emergency Fuel]`, `[Other]`\n\n"
        "• *Emergency Fuel:* Bot: `⛽ MANDATORY: Record short video showing fuel pump meter and truck odometer. Enter fuel amount spent in USD:` -> Driver: `35.00` -> Bot: `✅ EMERGENCY FUEL LOGGED: $35.00.`\n"
        "• *Other:* Bot: `🔧 Type short description of issue:` -> Driver: `Tire puncture repair` -> Bot: `💵 Enter amount spent in USD:` -> Driver: `10.00` -> Bot: `✅ EMERGENCY EXPENSE LOGGED: Tire puncture repair ($10.00).`\n\n"
        "5️⃣ *Driver Taps [I am Returning]:*\n"
        "• *Alert to Sales Rep:* `📍 DRIVER RETURNING TO BASE: TRIP-2026-00456. Live location stream has been turned off.`\n"
        "• *Return Menu to Driver (Button Card):*\n"
        "Header: `RETURNING TO BASE`\n"
        "Body:\n"
        "🚛 *RETURNING TO BASE: TRIP-2026-00456*\n"
        "────────────────────\n"
        "Live tracking has been turned off.\n"
        "When you arrive at the company depot, tap 'I Have Returned':\n"
        "Buttons: `[Emergency Charges]`, `[I Have Returned]`\n\n"
        "6️⃣ *Driver Taps [I Have Returned]:*\n"
        "🏁 *ARRIVAL CONFIRMED: TRIP-2026-00456*\n"
        "Welcome back, John Banda! Sales Admin for A. TG Hardware has been summoned for your return balancing session."
    )

    # PART 5
    part5 = (
        "📜 *TAGONESWA COMPLETE MESSAGE CATALOG (PART 5 OF 5)*\n"
        "════════════════════════════\n"
        "*STAGE 6: SALES ADMIN PHYSICAL BALANCING*\n\n"
        "1️⃣ *Balancing Summon to Company Sales Admin (Button Card):*\n"
        "Header: `BALANCING SESSION`\n"
        "Body:\n"
        "PHYSICAL BALANCING SESSION\n"
        "────────────────────\n"
        "Company: A. TG Hardware\n"
        "Trip: TRIP-2026-00456 | Route: Gweru\n"
        "Driver: John Banda | Truck: ZW 123 ABC\n"
        "────────────────────\n"
        "Customer Collections:\n"
        "• CUST-101: Exp $45.00 | Col $45.00 (CASH) [PAID]\n"
        "• CUST-102: Exp $60.00 | Col $60.00 (CASH) [PAID]\n"
        "• CUST-103: Exp $47.00 | Col $47.00 (CASH) [PAID]\n"
        "────────────────────\n"
        "Emergency Expenses:\n"
        "• EMERGENCY_FUEL: $35.00 (verify pump video)\n"
        "────────────────────\n"
        "Allowance Paid: $46.50\n"
        "Delivery Charges Collected: $152.00\n"
        "💵 Physical Cash Due: $152.00\n"
        "💳 Bank/EcoCash: $0.00\n"
        "────────────────────\n"
        "Verify physical cash and select status:\n"
        "Buttons: `[Balanced]`, `[Not Balancing]`\n\n"
        "2️⃣ *Balancing Outcome:*\n"
        "• *If [Balanced] tapped:* `✅ BALANCING SETTLED: TRIP-2026-00456. Forwarded to Logistics Manager for final closure!`\n"
        "• *If [Not Balancing] tapped:* Bot prompts: `⚠️ Enter variance amount in USD:` -> Admin enters `12.50` -> Bot: `📝 Enter audit notes:` -> Admin: `Pump video showed $47.50, reported $35.00` -> Bot: `⚠️ DISCREPANCY LOGGED: $12.50. Escalated to Manager!`\n\n"
        "────────────────────────────\n"
        "*STAGE 7: LOGISTICS MANAGER ADJUDICATION & TRIP CLOSED*\n\n"
        "3️⃣ *Manager Adjudication Card (Button Card):*\n"
        "Header: `TRIP ADJUDICATION`\n"
        "Body:\n"
        "TRIP ADJUDICATION NEEDED\n"
        "────────────────────\n"
        "Company: A. TG Hardware\n"
        "Trip: TRIP-2026-00456 | Route: Gweru\n"
        "Driver: John Banda | Truck: ZW 123 ABC\n"
        "────────────────────\n"
        "Discrepancy: $12.50\n"
        "Reason: Pump video showed $47.50, driver reported $35.00\n"
        "────────────────────\n"
        "Please approve or reject reimbursement / deduction:\n"
        "Buttons: `[Approve]`, `[Reject]`\n"
        "*(If [Reject] selected: $12.50 deficit automatically charged to driver pending ledger)*.\n\n"
        "4️⃣ *FINAL STAKEHOLDER BROADCASTS (CONFIDENTIALITY ENFORCED):*\n\n"
        "🔒 *A. Operational Staff Copy (Driver, Rep, Edward, Admin):*\n"
        "*(Sales Total is STRICTLY CONCEALED)*\n"
        "🏁 *TRIP CLOSED*\n"
        "────────────────────\n"
        "🏢 *Company:* A. TG Hardware\n"
        "🚛 *Trip:* `TRIP-2026-00456` | *Route:* Gweru\n"
        "👤 *Driver:* John Banda | *Truck:* ZW 123 ABC\n"
        "────────────────────\n"
        "💰 *Transport Collected:* $152.00\n"
        "💵 *Cash:* $152.00 | 💳 *Bank:* $0.00\n"
        "⚠️ *Emergency Expenses:* $35.00\n"
        "🍱 *Allowance Reconciled:* $46.50\n"
        "⚖️ *Balancing Status:* Settled (APPROVED)\n"
        "────────────────────\n"
        "✅ Trip operations successfully closed.\n\n"
        "👑 *B. Executive Management Copy (Zayn & Accounts):*\n"
        "*(Contains confidential Sales Total)*\n"
        "👑 *EXECUTIVE AUDIT: TRIP CLOSED*\n"
        "────────────────────\n"
        "Trip: `TRIP-2026-00456` | Company: A. TG Hardware\n"
        "Sales Total (Confidential): $14,200.00\n"
        "Transport Collected: $152.00\n"
        "Discrepancy: $0.00 (APPROVED)\n"
        "────────────────────\n"
        "Operational staff notified with sales total concealed."
    )

    parts = [part1, part2, part3, part4, part5]
    for idx, p in enumerate(parts, start=1):
        res = await meta_api.send_text_message(phone, p)
        logger.info(f"Delivered Part {idx} of 5 to {phone}: {res}")
        await asyncio.sleep(1.2)

    print("All 5 parts of the complete message catalog sent successfully!")

if __name__ == "__main__":
    asyncio.run(send_catalog_to_fazal())
